config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :apartments, only: [:new, :show, :create]
  
  get 'pages/index', to: 'static_pages#index', as: 'index'
  get 'pages/about', to: 'static_pages#about', as: 'about'
  get 'pages/contact', to: 'static_pages#contact', as: 'contact'
  
  devise_for :users

  get '404', to: 'application#not_found', as: 'not_found'

  get '*path', :to => 'application#not_found'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	validates :name, uniqueness: { case_sensitive: false },
				       presence: true
	validates :description, length: { maximum: 1000 }
	mount_uploader :image, ApartmentImageUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :apartment
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/apartments_controller.rb
require 'mechanize'
require 'htmlentities'

class ApartmentsController < ApplicationController
	def new
		@term = params[:q]
		@apartments = search_web_by_name(@term)
	end
	def show
		begin
			@apartment = Apartment.find(params[:id])
		rescue ActiveRecord::RecordNotFound => exception
			redirect_to not_found_path
		end
	end
	def create
		@apartment = Apartment.new(apartment_params)
		
		begin
			if @apartment.save
				get_details(@apartment)
				#get_reviews(@apartment)
			else
				@apartment = Apartment.find_by_name(apartment_params[:name])
			end
		rescue ActiveRecord::RecordNotFound => exception
			redirect_to not_found_path #TODO: give this local params for an error message
		end
		redirect_to apartment_path(@apartment)
	end

	private

    def apartment_params
	    params.require(:apartment).permit(:id, :name, :city, :state, :zip, :phone, :max_bedrooms, :min_bedrooms, :min_price, :max_price, :image_tag, :detail_page, :description, :image, :remote_image_url)
    end

    def search_web_by_name(name)
	  	agent = Mechanize.new
		coder = HTMLEntities.new

	  	page = agent.get('http://www.forrent.com/results.php?search_type=communityname&ssradius=30&page_type_id=name&main_field=' << coder.encode(name) << '&x=13&y=6&resultsPerPage=40')
	  	#page.search('a.searchMatchTitle')
	  	results = page.search('section.exactmatch')

	  	apartments = Array.new
		i = 0
		#make new apartment objects
		results.each do |result|
			apartment = Apartment.new
			apartment.name = result.at_css('a.searchMatchTitle').text
			apartment.city = result.at_css('span.locality').text
			apartment.state = result.at_css('abbr.region').text
			apartment.zip = result.at_css('span.postal-code').text

			#1-3 Bedroom | $890-$1455 #Studio-2 Bedroom | $444-$795 #3 Bedroom | $875
			#apartment.name = result.at_css('div.unit a').text.strip!
			rooms_and_price_match = /(?<min_bedrooms>\d+|studio)[-]?(?<max_bedrooms>(\d+)?)\s+bedroom\s+\|\s+\$?(?<min_price>(\d+|call\s+for\s+price))[-]?\$?(?<max_price>(\d+)?)/i.match(result.at_css('div.unit a').text.strip!)
			apartment.min_bedrooms = rooms_and_price_match[:min_bedrooms]
			if rooms_and_price_match[:max_bedrooms]
				apartment.max_bedrooms = rooms_and_price_match[:max_bedrooms]
			else
				apartment.max_bedrooms = rooms_and_price_match[:min_bedrooms]
			end
			apartment.min_price = rooms_and_price_match[:min_price]
			if rooms_and_price_match[:max_price]
				apartment.max_price = rooms_and_price_match[:max_price]
			else
				apartment.max_price = rooms_and_price_match[:min_price]
			end
			apartment.phone = result.at_css('a[name=propPhoneNumber]').text
			apartment.image_tag = result.at_css('img')[:src]
			apartment.detail_page = result.at_css('a.searchMatchTitle')[:href]
			apartments[i] = apartment
			i = i + 1
		end

		return apartments
    end

    def get_details(apartment)
    	agent = Mechanize.new
		coder = HTMLEntities.new

	  	page = agent.get(coder.encode(apartment.detail_page))

	  	apartment.description = page.search('aside#proShortDesc p').text
	  	apartment.address = page.search('span.street-address')[0].text
    end

    def get_reviews(apartment)
    	agent = Mechanize.new
		coder = HTMLEntities.new

	  	page = agent.get('http://www.apartmentratings.com/rate/SearchResults?query=' << apartment.name << '&page=0&sort=DEFAULT')

	  	#find the right apartment result
	  	#loop do
	  		results = page.search('div.result')
		  	results.each do |review|
		  		if review.at_css('div.address').text.include? apartment.address
		  			page = link_with(:text => review.at_css('span.complexName a').text).click
		  			#break
		  		end
		  	end
		  	#link = page.link_with(:text => 'next')
		  	#if link
		  	#	page.link_with(:text => 'next').click
		  	#else 
		  	#	page = nil
		  	#end
	  	#end
	  	if page
	  		#on result page
	  		apartment.reviews.create('did it omg')
	  	else
	  	end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def not_found
  	respond_to do |format|
      format.html { render template: 'error/not_found', layout: 'layouts/application', status: 404 }
      format.all  { render nothing: true, status: 404 }
    end
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password ) }
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email) }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  def about
  end
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	#global reusable page title	
	def full_title(page_title)
		base = "Review Jackal"
		if page_title.empty?
			base
		else
			"#{base} | #{page_title}"
		end
	end

	#link button to submit form
	def link_to_submit(*args, &block)
		link_to_function (block_given? ? capture(&block) : args[0]), "$(this).closest('form').submit()", args.extract_options!
	end
	
	def link_to_function(name, *args, &block)
     html_options = args.extract_options!.symbolize_keys

     function = block_given? ? update_page(&block) : args[0] || ''
     onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
     href = html_options[:href] || '#'

     content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end

	#magic to access devises gglobal user resource
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||+ Devise.mappings[:user]
	end


	def bootstrap_version
		"3.1.1"
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apartments/_search_form.html.erb
<%= form_tag(new_apartment_path, method: "get") do %>
  <%= label_tag(:q, "Search Apartments by Name:") %>
  <%= text_field_tag(:q, params[:q]) %>
  <%= submit_tag("GO") %>
<% end %>

app/views/apartments/new.html.erb
<% provide :title, "Search" %>
<h1>New (Search Results)</h1>
<%= render partial: 'search_form' %>
<% if @apartments %>
	<% @apartments.each do |apartment| %>
		<div class="row">
			<div class="col-lg-12">
			<%= image_tag(apartment.image_tag, class: 'image-responsive') %>
				<%= form_for apartment, url: {action: "create"}, :html => { :multipart => true } do |apartment_form| %>
					<%= apartment_form.hidden_field :name, :value => apartment.name %>
					<%= apartment_form.hidden_field :city, :value => apartment.city %>
					<%= apartment_form.hidden_field :state, :value => apartment.state %>
					<%= apartment_form.hidden_field :zip, :value => apartment.zip %>
					<%= apartment_form.hidden_field :phone, :value => apartment.phone %>
					<%= apartment_form.hidden_field :max_bedrooms, :value => apartment.max_bedrooms %>
					<%= apartment_form.hidden_field :min_bedrooms, :value => apartment.min_bedrooms %>
					<%= apartment_form.hidden_field :min_price, :value => apartment.min_price %>
					<%= apartment_form.hidden_field :max_price, :value => apartment.max_price %>
					<%= apartment_form.hidden_field :image_tag, :value => apartment.image_tag %>
					<%= apartment_form.hidden_field :detail_page, :value => apartment.detail_page %>
					<%= apartment_form.hidden_field :remote_image_url, :value => apartment.image_tag %>
					<%= link_to_submit( class: 'testing' ) do %>
						<strong><%= apartment.name %></strong>
					<% end %>
				<% end %>
			</div>
		</div>
	<% end %>
<% else %>
<h2>No Results</h2>
<% end %>

app/views/apartments/show.html.erb
<h1> apartments! </h1>
<h2> <%= @apartment.name %> </h2>
<%= image_tag(@apartment.image_url) %>
<p> city <%= @apartment.city %> </p>
<p> state <%= @apartment.state %> </p>
<p> zip <%= @apartment.zip %> </p>
<p> phone <%= @apartment.phone %> </p>
<p> maxbr <%= @apartment.max_bedrooms %> </p>
<p> minbr <%= @apartment.min_bedrooms %> </p>
<p> minprice <%= @apartment.min_price %> </p>
<p> maxprice <%= @apartment.max_price %> </p>
<p> imagetag <%= @apartment.image_tag %> </p>
<p> address <%= @apartment.address %> </p>
<p> desc <%= @apartment.description %> </p>

<% @apartment.reviews.each do |thisreview| %>
	<p> review <%= thisreview.body %> </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet"/>

  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid">
	    <div class="navbar-header">
	    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#rjackal-collapse">
	    		<span class="sr-only">Toggle navigation</span>
	    		<span class="icon-bar"></span>
	    		<span class="icon-bar"></span>
	    		<span class="icon-bar"></span>
	    	</button>
	        <%= link_to 'rJackal', root_path, class: 'navbar-brand' %>
	    </div>
	    <div class="collapse navbar-collapse" id="rjackal-collapse">
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li class="navbar-text">Logged in as <strong><%= current_user.email %></strong>.</li>
			    	<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
			    	<li><%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
				<% else %>
					<li><%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %></li>
					<li><%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %></li>
				<% end %>
			</ul>
		</div>
	  </div>
	</nav>

	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<%= yield %>		
			</div>
		</div>
	</div>
	<div class="navbar navbar-default navbar-fixed-bottom" role="navigation">
	  <div class="container">
		<ul class="nav navbar-nav">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path%></li>
        </ul>
	  </div>
	</div>
</body>
	<script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Page</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Page</h1>

app/views/static_pages/index.html.erb
<% provide(:title, "Home") %>
<h1>Home Page</h1>
<%= render partial: 'apartments/search_form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>